# -*- coding: utf-8 -*-
"""load_sequences.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmYI_SvLbwzbCVCfAzJvxCI3eliTnRno
"""
import os
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

# Emotion categories as per your mapping
EMOTION_MAP = {
    'happiness': 0,
    'disgust': 1,
    'repression': 2,
    'surprise': 3,
    'sadness': 4,
    'others': 5
}

# Image transformation for frames
frame_transform = transforms.Compose([
    transforms.ToTensor(),  # Converts to [0,1] tensor
    transforms.Normalize(mean=[0.5, 0.5, 0.5],
                         std=[0.5, 0.5, 0.5])
])

import os
import torch
from torch.utils.data import Dataset
from PIL import Image
import numpy as np
from glob import glob

class MicroExpressionDataset(Dataset):
    def __init__(self, root_dir, seq_len=16, transform=None, cache_dir=None):
        print("📂 Initializing MicroExpressionDataset...")
        self.root_dir = root_dir
        self.seq_len = seq_len
        self.transform = transform

        # Force cache directory to your specified path
        self.cache_dir = "/content/drive/MyDrive/deepfake-detection/microexpression/cache"
        os.makedirs(self.cache_dir, exist_ok=True)
        print(f"🗂 Cache directory set to: {self.cache_dir}")

        self.samples = []
        self.label_map = {
            "happiness": 0,
            "disgust": 1,
            "repression": 2,
            "surprise": 3,
            "sadness": 4,
            "others": 5
        }

        print("🔍 Scanning dataset folders...")
        for emotion in os.listdir(root_dir):
            emotion_dir = os.path.join(root_dir, emotion)
            if not os.path.isdir(emotion_dir):
                continue
            for video in os.listdir(emotion_dir):
                video_dir = os.path.join(emotion_dir, video)
                if os.path.isdir(video_dir):
                    self.samples.append((video_dir, self.label_map[emotion]))
        print(f"✅ Found {len(self.samples)} video samples across {len(self.label_map)} emotion categories.")

    def __len__(self):
        return len(self.samples)

    def _load_from_cache(self, cache_path):
        print(f"⚡ Loading from cache: {os.path.basename(cache_path)}")
        return torch.load(cache_path)

    def _save_to_cache(self, cache_path, data):
        torch.save(data, cache_path)
        print(f"💾 Saved to cache: {os.path.basename(cache_path)}")

    def __getitem__(self, idx):
        video_dir, label = self.samples[idx]
        cache_path = os.path.join(self.cache_dir, f"{os.path.basename(video_dir)}.pt")

        if os.path.exists(cache_path):
            return self._load_from_cache(cache_path)

        print(f"\n🎞 Processing video: {os.path.basename(video_dir)} | Emotion: {label}")

        # Load frames
        frame_files = sorted(glob(os.path.join(video_dir, "*.jpg")))
        print(f"🖼 Found {len(frame_files)} frames, loading...")
        frames = []
        for f in frame_files[:self.seq_len]:
            img = Image.open(f).convert("RGB")
            if self.transform:
                img = self.transform(img)
            else:
                img = torch.tensor(np.array(img)).permute(2, 0, 1).float() / 255.0
            frames.append(img)

        while len(frames) < self.seq_len:
            frames.append(torch.zeros_like(frames[0]))
        frames = torch.stack(frames)

        # Load AUs
        au_path = os.path.join(video_dir, "AUs.npy")
        if os.path.exists(au_path):
            aus = torch.tensor(np.load(au_path), dtype=torch.float32)
            if aus.shape[0] > self.seq_len:
                aus = aus[:self.seq_len]
            elif aus.shape[0] < self.seq_len:
                pad_len = self.seq_len - aus.shape[0]
                aus = torch.cat([aus, torch.zeros(pad_len, aus.shape[1])], dim=0)
            print(f"📊 Loaded AUs: {aus.shape}")
        else:
            print("⚠️ No AUs found, filling with zeros.")
            aus = torch.zeros(self.seq_len, 12)

        label_tensor = torch.tensor(label, dtype=torch.long)
        sample = (frames, aus, label_tensor)

        self._save_to_cache(cache_path, sample)
        return sample


if __name__ == "__main__":
    dataset = MicroExpressionDataset(
        root_dir="/content/drive/MyDrive/deepfake-detection/dataset/microexpression_processed",
        seq_len=16,
        transform=None
    )
    print(f"\n📦 Dataset ready. Total samples: {len(dataset)}")
    frames, aus, label = dataset[0]
    print("✅ Sample loaded")
    print("Frames:", frames.shape)
    print("AUs:", aus.shape)
    print("Label:", label)